name: Build and test pull requests

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: erlef/setup-beam@v1
      with:
        otp-version: '24'
        elixir-version: '1.12.2'
    - name: Test
      run: make test
